### ISSUE TITLE
Semantic Views Demo

### ISSUE THREAD

**Issue by mistermarco** [SU-SWS/Stanford-Drupal-Profile#16]
Semantic views adds a menu item to Navigation to a demo (seen in v.7). It seems like that would be confusing to new users. Should we remove it?

**Comment by jbickar** [comment]
Yes; thanks for filing the issue.

**Comment by jbickar** [comment]
Harder than it looks, apparently. Solving this (for now) by not enabling Semantic Views by default. Based on this thread: http://drupal.org/node/1013876, Views 3 provides some semantic markup options; I'll have to play with it some to see if it's still necessary to enable Semantic Views by default.
