### ISSUE TITLE
Disable Update Manager module

### ISSUE THREAD

**Issue by jbickar** [SU-SWS/Stanford-Drupal-Profile#17]
Update Manager module (update) gets enabled at install time. Doesn't appear in the standard install profile but somehow gets enabled anyhow.

HULK SMASH!

**Comment by rodrigoaguilera** [comment]
I just came from google. How did you solved it?

**Comment by rodrigoaguilera** [comment]
Onether silly search got me here
https://github.com/SU-SWS/Stanford-Drupal-Profile/blob/acc5dda8c2afeda931c0cbb581a3d35c7f8e0c72/stanford.profile#L148
Thanks!
