### ISSUE TITLE
Add new modules and dependencies

### ISSUE THREAD

**Issue by jbickar** [SU-SWS/Stanford-Drupal-Profile#4]
IDG included new modules in the stack as of October, 2011 (Stanford Events Importer, Feeds, Imagecache, Views Slideshow. The profile should be updated to reflect those.

**Comment by mistermarco** [comment]
Please check the updated list. Do we have a URL from Stanford Events Importer?

**Comment by jbickar** [comment]
projects[stanford_events_importer][type] = module
projects[stanford_events_importer][download][type] = file
projects[stanford_events_importer][download][url] = 'https://techcommons.stanford.edu/files/stanford_events_importer-6.x-1.0-beta6.tar.gz'

We'll need to add all of the dependencies too; I will commit and send a pull request.
